apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-pv
spec:
  storageClassName: volume-de-carros
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /tmp/logs
