pipeline {
    agent any
    tools{
        maven "mvn"
    }
    environment{
        DOCKER_CREDS= credentials('dockerhub')
    }

    stages {
        stage('Initialize') {
            steps {
                sh '''
                  echo "PATH=${PATH}"
                  echo "M2_HOME= ${M2_HOME}"
                '''
            }
        }
        stage('Git Checkout') {
            steps {
                git(
                    url: 'https://github.com/melissaostv/spring-carros.git',
                    branch: 'main')
                script{
                    TAG_VERSION = sh(script: 'git rev-parse --short HEAD', returnStdout:true).trim()
                }
            }
        }
        stage('Build') {
             steps{
                 sh "mvn -DskipTests clean package"

             }
             post{
                 success {
                     sh 'cp target/carros-0.0.1-SNAPSHOT.jar docker/'
                 }
             }
         }

          stage('Create Image') {
             steps{
                 echo "IMAGE VERSION: ${TAG_VERSION}"
                 sh "‘docker build . -t melissaost/spring-carros:${TAG_VERSION}"
                 sh "docker tag melissaost/spring-carros:${TAG_VERSION} melissaost/spring-carros:latest"
             }

         }
         stage('Push Image') {
             steps{
                sh "docker login --username=$DOCKER_CREDS_USR --password=$DOCKER_CREDS_PSW"
                sh "docker push melissaost/spring-carros:${TAG_VERSION}"
                sh "docker push melissaost/spring-carros:latest "
             }

         }
         stage('Update K8S') {
             steps{
               sh "kubectl set image deploy/app-carros-pod -n app-carros-pod app-carros-pod=melissaost/spring-carros:$TAG_VERSION"
                sh 'kubectl rollout status deploy/app-carros-pod -n app-carros-pod'
             }

         }
         stage('Clean Images') {
            steps{
                sh "docker image rm melissaost/spring-carros:${TAG_VERSION}"
                sh "docker image rm melissaost/spring-carros:latest"
            }

         }
    }
}